name: Build macOS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Compile on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew update
        brew install vlc cmake pkg-config

    - name: Download JUCE
      run: |
        git clone --depth 1 --branch master https://github.com/juce-framework/JUCE.git

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OnStage_Mac_App
        path: build/OnStage.app
